### ISSUE TITLE
Remove upload_test_pypi from release.yml

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#123]

**Comment by svenvanderburg** [comment]
Already done.

**Comment by gcroci2** [comment]
> Already done.

It's still there actually: https://github.com/DeepRank/deeprank-core/blob/main/.github/workflows/release.yml#:~:text=upload_test_pypi%3A,pypi.org/legacy/

**Comment by gcroci2** [comment]
Upload the package on Test Pypi can be done running the workflow (configured to run on the workflow_dispatch event) using the Actions tab on GitHub, GitHub CLI, or the REST API. 
When you publish a new release on Github, the upload on Pypi will be triggered. 
When you manually run the workflow from the actions tab, the upload on test Pypi will be triggered. So before publishing a new release, it would be good to manually run the workflow to test the package release.
