### ISSUE TITLE
Add CUDA support

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#132]
CUDA support should be added. It could be a parameter at the dataset generation, if true the tensors created are allocated to CUDA memory.

**Comment by cbaakman** [comment]
What is the best way to test this?

**Comment by gcroci2** [comment]
- I checked and the source code seems to have already cuda support. If available, the model is loaded to the GPU, otherwise to the cpu. Could you confirm this? @cbaakman 
- My other question now is, do we need to move the data tensors as well to cuda? I'm not familiar with it, maybe @cbaakman and @DTRademaker know more?

**Comment by cbaakman** [comment]
I added this check:
https://github.com/DeepRank/deeprank-core/blob/fba1352c1c5bc204b5eac933707b3b5330272655/tests/test_nn.py#L61
It confirms that the model parameters are cuda, on a machine where torch.cuda.is_available is true.

Also torch tensors have a .to method, where the device can be set to "cuda", if available.

**Comment by gcroci2** [comment]
> I added this check:
> 
> https://github.com/DeepRank/deeprank-core/blob/fba1352c1c5bc204b5eac933707b3b5330272655/tests/test_nn.py#L61
> 
> 
> It confirms that the model parameters are cuda, on a machine where torch.cuda.is_available is true.
> Also torch tensors have a .to method, where the device can be set to "cuda", if available.

Can we test this on a device that has cuda available? My Mac can't be used for this, since cuda is not supported at all by arm-based systems.

**Comment by cbaakman** [comment]
> > I added this check:
> > https://github.com/DeepRank/deeprank-core/blob/fba1352c1c5bc204b5eac933707b3b5330272655/tests/test_nn.py#L61
> > 
> > It confirms that the model parameters are cuda, on a machine where torch.cuda.is_available is true.
> > Also torch tensors have a .to method, where the device can be set to "cuda", if available.
> 
> Can we test this on a device that has cuda available? My Mac can't be used for this, since cuda is not supported at all by arm-based systems.

I did test it on my NVIDIA device. The test succeeds. I'm working on the data tensors now..
