### ISSUE TITLE
Add docs about feature modules

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#148]
In deeprankcore/feature/ folder, it would be convenient to have a clear explanation and listing of the features names and structure. In particular, we should:
- At the beginning of each feature module, write some general documentation about the module (and the feature) itself. 
- Then more specifically, list the features that the module produces (type, shape, high-level explanation). For example:
  - why does `hse` have three values for each data point? What do they represent?
  - What do `ic` values represent?

For each module, can we have a high-level explanation and a list of the generated features?
- amino_acid.py
- atomic_contact.py
- biopython.py
- bsa.py
- pssm.py
- sasa.py

**Comment by cbaakman** [comment]
What format should this documentation have. I presume you don't want to just add this to the README?

**Comment by gcroci2** [comment]
> What format should this documentation have. I presume you don't want to just add this to the README?

I think it would be useful to add something in the README to guide the user to build his/her own feature, so something like an example would be great. Then in each module, we can add either at the top or using more detailed doc strings info about the module itself, such as which node and edge features it generates.

**Comment by gcroci2** [comment]
Duplicated, now addressed by #239
