### ISSUE TITLE
Change definitions in storage.py

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#150]
In `deeprankcore.domain.storage.py` file, there are definitions for keys that are going to be defined in the hdf5 files containing graphs. 

- `score` could be changed to `label`. Any particular reason why we should keep `score`? We think that label would be clearer for the scope. 
- `node_data` and `edge_data` could be changed to `node_feat` and `edge_feat`, same as above.

**Comment by DaniBodor** [comment]
For now, we will keep it `score` because we want to verify whether people are using hdf5 data using the `score` nomenclature.
Potentially we can wright a replace-function to substitute all "score" for "label" in hdf5 files.

**Comment by gcroci2** [comment]
Since nobody is using deeprankcore at the moment, we can change the nomenclature and insert an Exception (in HDF5DataSet class) if an "old" version dataset is used.

**Comment by DaniBodor** [comment]
Similar to my [comment](https://github.com/DeepRank/deeprank-core/issues/145#issuecomment-1251938640) in #145, wouldn't it makes sense to unify the names of the `HDF5KEY_XXXX` variable name and the "xxxx" string value that they are stored under in the HDF5 files?

**Comment by gcroci2** [comment]
> Similar to my [comment](https://github.com/DeepRank/deeprank-core/issues/145#issuecomment-1251938640) in #145, wouldn't it makes sense to unify the names of the `HDF5KEY_XXXX` variable name and the "xxxx" string value that they are stored under in the HDF5 files?

I agree. For example, if we go for `target`, we should have `HDF5KEY_GRAPH_TARGET = "target"`

**Comment by DaniBodor** [comment]
How about this structure/nomenclature?
(see also [commit](https://github.com/DeepRank/deeprank-core/commit/8cfcd61d893bf58ddebca8931437c2ce2c9ca833) for comparison)

```bash
└── ppi-1ATN_1w:A-B
    ├── clustering
    │   ├── depth_0
    │   └── depth_1
    ├── edge_data
    │   ├── edge_names
    │   ├── edge_indices
    │   └── edge_features
    │       ├── coulomb
    │       ├── covalent
    │       ├── vanderwaals
    │       └── ...etc
    ├── node_data
    │   ├── node_name
    │   └── node_features
    │       ├── bsa
    │       ├── pssm
    │       ├── ic
    │       ├── hse
    │       └── ... etc
    └── target_data
        ├── bin_class
        ├── irmsd
        └── ... etc

```

**Comment by gcroci2** [comment]
> How about this structure/nomenclature? (see also this [commit](https://github.com/DeepRank/deeprank-core/commit/8cfcd61d893bf58ddebca8931437c2ce2c9ca833) for comparison)
> 
> ```shell
> └── ppi-1ATN_1w:A-B
>     ├── clustering
>     │   ├── depth_0
>     │   └── depth_1
>     ├── edge_data
>     │   ├── edge_names
>     │   ├── edge_indices
>     │   └── edge_features
>     │       ├── coulomb
>     │       ├── covalent
>     │       ├── vanderwaals
>     │       └── ...etc
>     ├── node_data
>     │   ├── node_name
>     │   └── node_features
>     │       ├── bsa
>     │       ├── pssm
>     │       ├── ic
>     │       ├── hse
>     │       └── ... etc
>     └── target_data
>         ├── bin_class
>         ├── irmsd
>         └── ... etc
> ```

Nice, seems much better to me! I just changed `node_name` to `node_names`, to be coherent with the edges. 

@cbaakman Does this work for you?

**Comment by DaniBodor** [comment]
> Nice, seems much better to me! I just changed `node_name` to `node_names`, to be coherent with the edges.

The difference is that the `edge_names` contains the names of the 2 nodes that it connects, whereas `node_name` only has the one name.

> For the clustering, it's fine to not have another sublevel for me, but we should indicate somewhere the type of clustering (e.g., mcl).
OK!

**Comment by gcroci2** [comment]
> > Nice, seems much better to me! I just changed `node_name` to `node_names`, to be coherent with the edges.
> 
> The difference is that the `edge_names` contains the names of the 2 nodes that it connects, whereas `node_name` only has the one name. If we want it coherent, then I think singulars make more sense.
> 

Okay makes sense, fine for me!

I was thinking, what about removing edge_ and node_ inside edge_data and node_data groups?

```bash
└── ppi-1ATN_1w:A-B
    ├── clustering
    │   ├── depth_0
    │   └── depth_1
    ├── edge_data
    │   ├── names
    │   ├── indices
    │   └── features
    │       ├── coulomb
    │       ├── covalent
    │       ├── vanderwaals
    │       └── ...etc
    ├── node_data
    │   ├── names
    │   └── features
    │       ├── bsa
    │       ├── pssm
    │       ├── ic
    │       ├── hse
    │       └── ... etc
    └── target_data
        ├── bin_class
        ├── irmsd
        └── ... etc

```

**Comment by DaniBodor** [comment]
> I was thinking, what about removing edge_ and node_ inside edge_data and node_data groups?

I left it in, because I think it's nice to know what we are talking about just from the variable name, without knowing which group it's in. Also helps not confusing them while coding. For the individual features, it's less of an issue, because the features have different names anyway

**Comment by gcroci2** [comment]
> > I was thinking, what about removing edge_ and node_ inside edge_data and node_data groups?
> 
> I left it in, because I think it's nice to know what we are talking about just from the variable name, without knowing which group it's in. Also helps not confusing them while coding. For the individual features, it's less of an issue, because the features have different names anyway

But you would need to navigate into `node_data` anyway before extracting `node_name`, for example. The thing is that now by looking at the original structure and the new one, there are many redundancies in the latter, and names are longer (usually the shorter the better). If we need to specify that `name` refers to node even if it is inside `node_data` group, then I would say that it could stay outside as well because it's self-explainatory. I think that the hierarchy makes sense (and I really like it), but only if it removes such redundancies. Otherwise, also the old structure is sort of fine.

**Comment by DaniBodor** [comment]
For this issue and #145:

- [ ] Update FEATURENAMEs (done until res_type)
    - make sure to search for strings as well
    - move featurenames into dict instead of individual strings??
- [ ] Fix clustering groups/names
- [ ] Move domain.storage to domain.feature instead
    - delete domain.storage
- [ ] Check featurename changes suggested by Giulia
- [ ] Assign currently unused features

**Comment by DaniBodor** [comment]
# My to do list for domain_overhaul branch (this issue and #145):

## Update FEATURENAMEs
- [x] ***ALL DONE?***
  - [x] Move features into separate submodules
    - [x] Rename features for brevity & clarity
    - [x] Check featurename changes suggested by Giulia
  - [x] Replace string calls for variable in feature submodules
  - [x] Update README and quickstart
    - [x] Use module calls instead of strings here as well
  - [x] Move domain.storage
    - [x] delete domain/storage.py
  - [x] delete domain/feature.py
  - [x] move former `HDF5KEY_GRID_XXXX` stuff into the module where its used

## ~~Update clustering groups/names~~
- [ ] ~~***ALL DONE?***~~
  - [ ] ~~Update cluster naming to one level shallower and prefixing the clustering-type~~
    - [ ] ~~Test on files whether this works as it's supposed to; i.e. `"clusters\mcl_depth0"`~~
        - ~~especially suspect is Trainer.py lines 721/728: `method_grp.create_dataset(groups.DEPTH0, data=cluster.cpu())` (and DEPTH1)~~
  - Decided against this after all; potentially there can be multiple clusters in the same HDF5 file and nicer organized to have them in subfolders I think (plus less chance of making mistakes)

## Changes dependent on other PRs
- [ ] ***ALL DONE?***
  - [ ] Finalize task PR (#200) and atom feature PR (#195) and merge them into this branch; then: 
    - [ ] Make a targettypes module inside domain or inside domain.features for default targets
    - [ ] Move atom feature names into domain/features/nodefeats.py

## Pytesting 
- [ ] ***ALL DONE?***
  - [ ] Remake the *.pdb files
    - I'll need Giulia's help for this
  - [ ] Run Pytest to make sure I didn't break anything

## Specific feature stuff
- [ ] ***ALL DONE?***
  - [ ] Assign currently unused features
    - [x] CHARGE + DIFFCHARGE
    - [ ] CHAINID
      - Not sure whether this is relevant standalone (unlikely) or just as intermediary to SAMECHAIN
      - Don't know how to get this info
        - models/structure has a Chain class
    - [ ] SAMECHAIN always set to 1
        - tools.visualization, line 83: `graph.edges[node1_name, node2_name][edgefeats.SAMECHAIN] = 1.0` without any if statement
        - currently there is no chain info anyway, but once we have that, this would be useful
        - would need to find out how to extract CHAINID from the two nodes of this edge
    - [x] check whether all other features are actually assigned
  - [ ] Remove VARIANTCONSERVATION or add VARIANTXXXXXXX for other features
    - If we make them, then rethink nomenclature
  - [x] Research what happens when onehots are subtracted (feature.aminoacid.py > DIFFPOLARITY)
    - It turns into a 0/1/-1 -type vector, so A-OK  

## Define classes used only in models.amino-acid internally (DONE)
- [x] ***ALL DONE?***
  - [x] Move AminoAcid and Polarity classes into deeprankcore/models/amino-acid
    - [x] delete deeprankcore/domain/amino-acid and deeprankcore/models/polarity
