### ISSUE TITLE
Explore plotting metrics

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#151]
We should make sure that the actual plotting metrics (in deeprankcore/Metrics.py):
- plots epochs vs metrics (e.g. accuracy)
- plots epochs vs loss
- add examples in the docs about how to get the above plots

**Comment by cbaakman** [comment]
For the plotting, one could implement new metrics exporters, as in https://github.com/DeepRank/deeprank-core/blob/main/deeprankcore/models/metrics.py

**Comment by gcroci2** [comment]
In the old Deeprank-GNN, in NeuralNet class there were methods such as [`get_metric`](https://github.com/DeepRank/Deeprank-GNN/blob/3a59d7473824cf3e6e33b08dcd57fdd60151a969/deeprank_gnn/NeuralNet.py#L539) and `plot_loss` that are absent from deeprank-core. Why were they removed?

Also, in deeprankcore.models.metrics there are already exporters such as OutputExporter and TensorboardBinaryClassificationExporter that seem very handy, but I don't know how to use them, and I don't understand it from the tests. Could you help?

@cbaakman

**Comment by gcroci2** [comment]
See issue #188
