### ISSUE TITLE
Explore `classes` input parameter of GraphDataset

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#156]
Explore what `classes` input parameter does in `NeuralNet` class, and if it's actually needed.
From the docs in NeuralNet.py: 
```
classes (list, optional): define the dataset target classes in classification mode. Defaults to [0, 1].
```
- If we don't support multiclassification tasks, it should be documented explicitly. From the code it seems that we don't support it (the init of the `NeuralNet` class set the threshold considering only two possible classes, for example).
- If you are not in the [0,1] target case, `NeuralNet` class requires you to explicitly specify the classes in case of a classification task.
   - Would be useful to detect them automatically from the target values? The only problem (unrealistic) that I see in this is in cases in which your dataset doesn't contain all the two possible classes.
   - We should explicitly write that you need to indicate the two possible values (of the right type) that the target class can have. Even if I don't think this makes any difference in the process, am I wrong?
   - What is the advantage for the user to manually filling in the possible values of the classes? If we support only binary classification (and I think this is the case), there are always going to be two possible values, and they will be mapped to [0, 1] at a certain point anyway.

**Comment by cbaakman** [comment]
Deeprank supports more than two class labels. I've never tried it though, but I think it should be doable and available. There should also be some mechanism that handles class names, rather than just working with 0 and 1.

The threshold variable seems unused and I don't think it can be used in the current setup, where deeprank will create one output channel for each class.

**Comment by gcroci2** [comment]
- We do support multiclassification tasks.
- We deleted the threshold parameter.
- If `classes` argument is None, it is set up to [0, 1] and it is printed in the log.
