### ISSUE TITLE
Explore `threshold` input parameter of NeuralNet

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#157]
In `NeuralNet` class, `threshold` input parameter is used to compute binary classification metrics, and defaults to `4.0`.

- The default for `classes` parameter is [0, 1], so I think it would be handy to have a default threshold set to `0.5`.
- If the threshold is `None` and we are in a classification task, it is set to `classes[1]`, that for example in the default case of target [0, 1] would be `1`. This is not correct, right?
- If the task is regression and the threshold is `None`, the threshold is set to 0.3. Why and how is a threshold used in a regression task?

**Comment by cbaakman** [comment]
The threshold field of the NeuralNet class isn't used anywhere. I think it should be removed.
