### ISSUE TITLE
Explore `transform` parameter of `GraphDataset`

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#158]
In `Trainer` class, `transform` input parameter takes in a torch_geometric.data.Data object and returns a transformed version of the data.
- The user should be able to set the feature and the transformation that should be applied to the feature. Right now the code seems to transform the entire dataset. What if the user wants to transform multiple features in different ways?
- Is `transform` only for nodes features?
- `edge_feature_transform` should be included in `transform`, or both parameters should have a more consistent name (e.g., edge_feat_transform and node_feat_transform, respectively).
- Why the `edge_feature_transform` default is `lambda x : np.tanh(-x/2 + 2) + 1` and why is it applied to all the edge features?

Will be solved by #326

**Comment by cbaakman** [comment]
I've never written or used this part of the code. But it seems that transform can be used on all of the data object, including the edge features. I have no idea why deeprank has an additional edge_feature_transform input parameter.

**Comment by DaniBodor** [comment]
it's also unclear what the difference between `transform` and `pre_transform` is

**Comment by DaniBodor** [comment]
This issue may be solved by #237

**Comment by gcroci2** [comment]
We decided to remove for now `transform` parameter since it's never used and it adds "noise" to the API documentation
