### ISSUE TITLE
Explore community_pooling module

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#160]
Some questions:
- What does this module do?
- How does the clustering work? 
- Is it needed for all neural network types or only for some? 

Maybe rename the module once things become clear.

**Comment by cbaakman** [comment]
The ginet network model uses preclustered data in the forward. but the actual clustering is done in NeuralNet.
Since not all network models use preclustered data, I think the clustering should be optional.

**Comment by gcroci2** [comment]
In the Trainer class, if `clustering_method` is not None and one between `mcl` and `louvain`, `_precluster` internal method is called. This is applied to all the dataset given to the Trainer. 

### Digging into `_precluster` internal method
In this method, each data point graph is loaded (calling `load_one_graph` method) and the torch_geometric.data.data Data instance is returned (called `data`).
For each data point (thus for each data point Group), a new subGroup called `clustering` is created in the hdf5 file.
In this `clustering` subGroup, a Dataset called "depth_0" is created taking as input `data.edge_index`, `data.num_nodes` and the clustering method, through the `community_detection` function. Depending on the method, a torch tensor representing the cluster is created and used to populate the Dataset "depth_0".
- It's not clear what such a cluster tensor represents. The documentation says "clusters of nodes based on the edge attributes (distances)", but still I am not getting it.

Such torch tensor (called `cluster`) is then also used as input to the function `community_pooling`, together with `data`, to return an updated version of `data`, that now is a `Batch` instance ("pyotrch geometric data object describing a batch of graphs as one big disconnected graph"). 
- Also this step is not clear to me. Why is it needed?

Such an updated version of `data` is then used as input to `community_detection`, to return another cluster vector that is used to populate another Dataset in the subGroup `clustering`, called "depth_1".
- Same as above.

- Overall, the entire procedure logic is unclear to me.
  - [ ] Is this knowledge sort of granted if you are used to training networks with graphs?
  - [ ] Is there any documentation online (blog posts, tutorials, ...) that can help us to understand why this is needed at all (from a theoretical point of view), and if the procedure is the correct one?

In foutnet.py, ginet.py and sgat.py, `community_pooling` is called in the forward method of the networks.  
From what I see in their code, only the updated version of `data`, given as output by `community_pooling` called in trainer.py (and passed to the network) is used by the networks to retrieve cluster tensors through `get_preloaded_cluster` function. But then the `community_pooling` function is called _again_ in the forward method.
- [ ] Why is `community_pooling` called again in the forward?
- [ ] What is then the point to save computed clusters in "depth_0" and "depth_1" Datasets, if they are never actually used?

**Comment by cbaakman** [comment]
I didn't write the clustering code, so I might be wrong.

I know that the cluster tensor lists for each node (index) to what cluster (number) it belongs:
```
cluster = [
 0,  # node 0 belongs to cluster 0
 0,  # node 1 belongs to cluster 0
 1,  # node 2 belongs to cluster 1
 1,  # node 3 belongs to cluster 1
 ...
]
```
This is compatible with torch_geometry's pooling functions, which are used in the deeprank `community_pooling` function to generate updated feature values for each cluster.

Some neural networks, like `FoutNet`, use the clustered features to save time.

@manonreau, @NicoRenaud, do you have any additional comments on this?

**Comment by gcroci2** [comment]
https://medium.com/data-science-in-your-pocket/community-detection-in-a-graph-using-louvain-algorithm-with-example-7a77e5e4b079

**Comment by NicoRenaud** [comment]
Sorry I didn’t see any of this before. Good explanation @manonreau ! I had a chat with @gcroci2 today, I hope we cleared the last details !

**Comment by gcroci2** [comment]
> Sorry I didn’t see any of this before. Good explanation @manonreau ! I had a chat with @gcroci2 today, I hope we cleared the last details !

Yes indeed :)

**Comment by gcroci2** [comment]
In the Trainer class, if `clustering_method` is not None and one between `mcl` and `louvain`, `_precluster` internal method is called. This is applied to all the dataset given to the Trainer. 

### Digging into `_precluster` internal method
In this method, each data point graph is loaded (calling `load_one_graph` method) and the torch_geometric.data.data Data instance is returned (called `data`).
For each data point (thus for each data point Group), a new subGroup called `clustering` is created in the hdf5 file.
In this `clustering` subGroup, a Dataset called "depth_0" is created taking as input `data.edge_index`, `data.num_nodes` and the clustering method, through the `community_detection` function. Depending on the method, a torch tensor representing the cluster is created and used to populate the Dataset "depth_0".
- It's not clear what such a cluster tensor represents. The documentation says "clusters of nodes based on the edge attributes (distances)", but still I am not getting it. _It finds communities and it contains indexes referring to the community to which each residue belongs (community_detection method)_

Such torch tensor (called `cluster`) is then also used as input to the function `community_pooling`, together with `data`, to return an updated version of `data`, that now is a `Batch` instance ("pyotrch geometric data object describing a batch of graphs as one big disconnected graph"). _The communities are "pooled" using community_pooling function (each community is assigned to a point, doing either the maximum or the average); this could be done iteratively, but since the molecules with which they were experimenting weren't so big, they did it once and they did twice the community detection thing._
- Also this step is not clear to me. Why is it needed?

Such an updated version of `data` is then used as input to `community_detection`, to return another cluster vector that is used to populate another Dataset in the subGroup `clustering`, called "depth_1".
- Same as above.

- Overall, the entire procedure logic is unclear to me.
  - [ ] Is this knowledge sort of granted if you are used to training networks with graphs?
  - [ ] Is there any documentation online (blog posts, tutorials, ...) that can help us to understand why this is needed at all (from a theoretical point of view), and if the procedure is the correct one?

In foutnet.py, ginet.py and sgat.py, `community_pooling` is called in the forward method of the networks.  
From what I see in their code, only the updated version of `data`, given as output by `community_pooling` called in trainer.py (and passed to the network) is used by the networks to retrieve cluster tensors through `get_preloaded_cluster` function. But then the `community_pooling` function is called _again_ in the forward method.
- [ ] Why is `community_pooling` called again in the forward?
- [ ] What is then the point to save computed clusters in "depth_0" and "depth_1" Datasets, if they are never actually used?


_In general, this was taken from social graph methods; see posts like https://medium.com/data-science-in-your-pocket/community-detection-in-a-graph-using-louvain-algorithm-with-example-7a77e5e4b079 to better understand the two methodologies (at least Louvain)_
