### ISSUE TITLE
Fix AttributeError in test_integration

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#161]
An integration tests for the whole pipeline (data preprocessing - training a model - evaluation, see PR #162) fails with the following error:

```
test_integration.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../deeprankcore/DataSet.py:183: in __init__
    self.check_node_feature()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'HDF5DataSet' object has no attribute 'index_complexes'") raised in repr()] HDF5DataSet object at 0x286d03160>

    def check_node_feature(self):
        """Checks if the required node features exist"""
        f = h5py.File(self.database[0], "r")
        mol_key = list(f.keys())[0]
        self.available_node_feature = list(f[mol_key + "/node_data/"].keys())
        f.close()
    
        if self.node_feature == "all":
            self.node_feature = self.available_node_feature
        else:
            for feat in self.node_feature:
                if feat not in self.available_node_feature:
                    print(feat, " node feature not found in the file", self.database[0])
                    print("Possible node feature : ")
                    print("\n".join(self.available_node_feature))
                    # raise ValueError('Feature Not found')
>                   sys.exit()
E                   SystemExit

../deeprankcore/DataSet.py:253: SystemExit
----------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------
   Checking dataset Integrity
type  node feature not found in the file /var/folders/js/v54t24f101585t5fkkx3qpkh0000gn/T/tmpvt9eiqr9/test-preprocess-14984.hdf5
Possible node feature : 
pos
sasa
```

**Comment by gcroci2** [comment]
Any ideas about this error? @cbaakman

**Comment by cbaakman** [comment]
It seems this error is thrown when the list in Dataset's 'node_feature' argument, does not correspond to the node features actually in the hdf5 file. I can't say more about this, since I don't know what arguments and HDF5 file you're using.

Where can I find this test_integration.py ?

**Comment by gcroci2** [comment]
> It seems this error is thrown when the list in Dataset's 'node_feature' argument, does not correspond to the node features actually in the hdf5 file. I can't say more about this, since I don't know what arguments and HDF5 file you're using.
> 
> Where can I find this test_integration.py ?

As I wrote above, in this PR: **https://github.com/DeepRank/deeprank-core/pull/162**. 

`deeprank.preprocess` takes as input feature_modules, which should be a list, and for sure the problem is that I'm not passing the same features that then I use in HDF5DataSet, as you were saying. But HDF5DataSet takes as input two distinct `node_feature` and `edge_feature` lists, so it's not clear to me if I have to pass `node_feature` + `edge_feature` to `preprocess`.  These are the features that I'd like to have in the HDF5DataSet instance:
```
node_feature=["type", "polarity", "bsa", "depth", "hse", "ic", "pssm"]
edge_feature=["dist"]
```

When understood, I should:
- [ ] Improve the documentation about preprocess parameter `feature_modules`
- [ ] Add tests in test_preprocess.py for different features
- [ ] Improve error displayed if in the second step (HDF5DataSet instantiation) you pass in features not selected with the first step (preprocess)

**Comment by cbaakman** [comment]
The feature modules used during the preprocessing determine what node and edge features are computed. Some feature modules produce more than one particular feature.

https://github.com/DeepRank/deeprank-core/blob/ac293185fdabad25fca3d28f67bed71a71faabe5/tests/test_integration.py#L43
So the test only uses the sasa module, which will only produce a node features named "sasa". This does not correspond to the Dataset node_feature and edge_feature lists. And that's most likely the reason for that error.

Indeed, there should be some kind of documentation on the feature modules and what features they produce.

Optionally, you could test for every feature that can be generated in the preprocessing step, but that could also be done by making the test simply inspect the hdf5 file.

We could indeed give the error a longer message, saying that the feature wasn't generated during preprocessing.

**Comment by gcroci2** [comment]
> The feature modules used during the preprocessing determine what node and edge features are computed. Some feature modules produce more than one particular feature.
> 
> https://github.com/DeepRank/deeprank-core/blob/ac293185fdabad25fca3d28f67bed71a71faabe5/tests/test_integration.py#L43
> 
> 
> So the test only uses the sasa module, which will only produce a node feature named "sasa". This does not correspond to the Dataset node_feature and edge_feature lists. And that's most likely the reason for that error.
> Indeed, there should be some kind of documentation on the feature modules and what features they produce.

I agree, indeed I opened [an issue about this](https://github.com/DeepRank/deeprank-core/issues/148) in the new kanban board I created for improving this kind of things.

As you can see from the PR I added some comments and documentation to the code. Now running the integration test with all features modules, I get an error about the target:
```
deeprankcore/DataSet.py:335: ValueError
===================================================================================================== warnings summary =====================================================================================================
../../../../../../miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py:4
../../../../../../miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py:4
  /Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================================= short test summary info ==================================================================================================
FAILED tests/test_integration.py::test_integration - ValueError: Target irmsd missing in residue-graph-101M:A:9:Alanine->Phenylalanine
```

You can reproduce the test using this file: https://github.com/DeepRank/deeprank-core/blob/integration_tests/tests/test_integration.py

**Comment by cbaakman** [comment]
The target score iRMSD seems to be calculated here: https://github.com/DeepRank/deeprank-core/blob/4e8823758ba03f824b4281f5689cb6a335ab2f6c/deeprankcore/tools/score.py#L24

You could either remove iRMSD from the test or add it to the hdf5 file, like this:
https://github.com/DeepRank/deeprank-core/blob/4e8823758ba03f824b4281f5689cb6a335ab2f6c/deeprankcore/GraphGenMP.py#L145

**Comment by gcroci2** [comment]
> The target score iRMSD seems to be calculated here:
> 
> https://github.com/DeepRank/deeprank-core/blob/4e8823758ba03f824b4281f5689cb6a335ab2f6c/deeprankcore/tools/score.py#L24
> 
> You could either remove iRMSD from the test or add it to the hdf5 file, like this:
> 
> https://github.com/DeepRank/deeprank-core/blob/4e8823758ba03f824b4281f5689cb6a335ab2f6c/deeprankcore/GraphGenMP.py#L145

I didn't indicate any target in SingleResidueVariantResidueQuery. I think it's important to:
- list all possible targets that can be used with query.py classes
- if no targets are passed to the class init, copy target data from query to graph

**Comment by cbaakman** [comment]
I think it tries to take irmsd from the hdf5 file, because the dataset is given the argument "target=irmsd".

**Comment by cbaakman** [comment]
When training a network, you can only have one target right? Or should we combine all the targets in the hdf5 files into one output variable?

Currently deeprank is set up to ether
- have one target variable
- have zero target variables

An HDF5 file can have many target scores in it though, but the dataset class has to pick one.
