### ISSUE TITLE
Add `atom` node feature

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#168]
It would be nice if we have `atom_type` as a feature (we can obtain them from the node information from the hdf5 file).
- Could you copy-paste here the code you use to obtain this info? @DTRademaker 
- Please list here all possible values that the feature can have.

**Comment by DanielTobiasRademaker** [comment]
`
def extractAtoms(fileName):
	return [[float(line[30:38]),\
			float(line[38:46]),float(line[46:54]), line[17:20], line[77], line[13:15], line[21]] \
				for line in open(fileName).read().replace(' OX', ' O ' ).split('\n') \
						if line.startswith('ATOM ') and line[77]!='H']
						
# Extract coordinates, chainID, atom, element and aminoacid information from pdb
def raw2proc(pdbFile):
	pdb 		= extractAtoms(pdbFile)
#	xyz 		= torch.tensor([i[:3] for i in pdb])
#	chain 		= [i[-1] for i in pdb]
	atom  		= [i[-2].strip() for i in pdb]
#	element  	= [i[-3] for i in pdb]
#	amino_acids = [i[-4] for i in pdb]
#	return xyz, chain, atom, element, amino_acids
	return atom

# All possible values
atoms = ['OX', 'CZ', 'NE', 'SG', 'N ', 'O ', 'OH', 'CE', 'C ', 'NZ', 'OE', 'OD', 'OG', 'NH', 'CG', 'CD', 'CA', 'SD', 'CH', 'CB', 'ND']`

**Comment by DaniBodor** [comment]
It would be handy to have #147 resolved first, which explains what is required for a new feature module

**Comment by DaniBodor** [comment]
@gcroci2 ,

did you mean an entire module for atom graphs, including the element (atom type), atomic charge, etc? Or did you just mean a single feature for the element?

**Comment by DaniBodor** [comment]
> did you mean an entire module for atom graphs, including the element (atom type), atomic charge, etc? Or did you just mean a single feature for the element?

note to self:
- if single feature --> use amino_acid.py
- if feature module --> use atom.py

**Comment by gcroci2** [comment]
> @gcroci2 ,
> 
> did you mean an entire module for atom graphs, including the element (atom type), atomic charge, etc? Or did you just mean a single feature for the element?

I mean a single feature for the element, which is the atomic type. It could be placed in deeprankcore.feature.amino_acid

**Comment by gcroci2** [comment]
@DaniBodor Additional context: right now, `FEATURENAME_AMINOACID` refers to the feature called `type` in the hdf5 file (see deeprankcore.domain.feature). It indicates the type of residue (amino acid), and it is represented with a one-hot encoding of the residue, assuming that there are 20 possible residues. Thus, this feature should be called `res_type` or something similar to indicate that the type refers to the residue. Then, I think we should have two different cases:
1. If node.id is a Residue (see deeprankcore.feature.amino_acid), then we only have `res_type`. It is already like this, except for the name `type` instead of `res_type`.
2. If node.id is an Atom, then we should have both `res_type` and `atom_type`, the latter not implemented at the moment. We could to the same thing that we do for residues, which is one-hot encoding the string that represents the type.

**Comment by DaniBodor** [comment]
> I checked the code and I don't think we have a module for specific atomic features right now, right? @cbaakman If this is the case, I would create a new module called like atom.py in which for now we only calculate the atomic type (so only a single feature there). We may add other features in the future.

The information for those is actually present. Basically generic features of the different elements. It is used for example to calculate some of the edge features already. So, I will create a small module to get all of these, I guess

**Comment by DaniBodor** [comment]
I also still need to move the atom features into domain/feature once that branch is merged
