### ISSUE TITLE
Explore `add_features_for_residues` function in feature/atomic_contact.py

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank-core#207]
Currently nested for loops are used to compare each atom of one residue against each atom of the other residue and extract information one comparison at a time.
There is likely a way to get the sum/minimum/etc (whichever is applicable) in one shot, perhaps using some numpy function. 

This is likely to be faster and definitely more pythonic and readable.

**Comment by DTRademaker** [comment]
Sound like a smart idea! Especially considering that the people using this framework will always have to convert a huge amount of files.
