### ISSUE TITLE
Feature classes for CNNs | inherent features in Atom and Residue classes

### ISSUE THREAD

**Issue by rgayatri** [DeepRank/deeprank-core#21]
- In addition to Coos's issue "classes required: Features" we would need separate classes for forcefield params (Evdw, Eelec) and PSSMs for CNNs. 
- Another aspect to be finalized is the set of structural features associated with Atom and Residue classes. 
- Resolve potential redundancies.

**Comment by DaniBodor** [comment]
This looks like something that has been done ages ago (before I joined the project), but forgot to be closed?

**Comment by gcroci2** [comment]
> This looks like something that has been done ages ago (before I joined the project), but forgot to be closed?

Indeed, I am closing it
