### ISSUE TITLE
Create basic transformations module

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#237]
It would be nice to have a module with some basic normalization/standardization functions that can be applied to different features of the HDF5Dataset instances.

Such operations should be performed after the definition of HDF5Dataset instances but before the Trainer fitting.

**Comment by DaniBodor** [comment]
also reorganize a bit how these are handled by GraphDataset

**Comment by gcroci2** [comment]
This issue may close #158

**Comment by gcroci2** [comment]
Useful post https://towardsdatascience.com/the-best-format-to-save-pandas-data-414dca023e0d
