### ISSUE TITLE
Evaluate whether grid.py module is useful for integrating CNNs and GNNs

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank-core#243]
delete file if not used after integration

**Comment by gcroci2** [comment]
Steps to create an hdf5 file containing graphs mapped to grids:
- `graph = query.build(feature_modules)`
- `grid_settings = GridSettings(points_count, size)`, being `points_count` the number of points on one edge of the cube and `size` the length in Å of one edge of the cube.
- `graph.write_as_grid_to_hdf5(hdf5_path, grid_settings, MapMethod.FAST_GAUSSIAN)`
- `MapMethod` can be GAUSSIAN, FAST_GAUSSIAN, BSP_LINE, NEAREST_NEIGHBOURS

**Comment by gcroci2** [comment]
grid_info = {
    "number_of_points": [35,30,30],
    # "number_of_points": [1,1,1],
    "resolution": [1.,1.,1.]
}

**Comment by gcroci2** [comment]
I opened a [Kanban board](https://github.com/DeepRank/deeprank-core/projects/7) for listing issues related to this task.
