### ISSUE TITLE
Fix amino acid charges

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank-core#271]
We realized that all amino acid "charges" are negative values. This does not stroke with actual charge of amino acids (which can be positive, negative, or uncharged).
- Likely, this feature represents something else than actual charge, but it is currently unclear what. Once this becomes clear, we should rename the feature
- We currently have a Polarity for each amino acid as well (Pos/Neg/Polar/Apolar). Is this sufficient, or do we want to add amino acid charge values as well as a separate feature?
  - I assume adding the feature never hurts, as it can just be not selected away in GraphDataset class if it turns out to not add anyth

**Comment by DaniBodor** [comment]
After researching amino acid/residue properties for some time:
- I failed to find out what is encoded by the current "charge" value in domain/aminoacidlist.py. I suspect that it is some error or mistake and doesn't represent any actual property of the amino acid.
- Amino acid charges are +1, 0, or -1, which makes sense given that they are usually just listed as positive, negative, or neutral (neutral is further subdivided into polar/apolar). Given that we have Polarity as an amino acid feature, charge can probably be dropped.
- Amino acids have a defined isoelectric point (pI), the pH at which they a molecule has no net electric charge). I guess this is the closest thing to what is currently defined as charge. However, the values are in no way similar to the current charge values.
- I found some other typical chemicophysical amino acid properties that may (or may not) be informative structurally. I can add these to domain/aminoacidlist.py
  - pI (as mentioned above)
  - molecular/residue mass (different from current "size", which measures the "number of heavy atoms"
  - apolar residues chains can be further subdivided into aromatic (containing CH rings), aliphatic (strictly straight CH-chains), and "other" (Pro, Gly)
    - not sure what the best way to implement this is, given that apolars are still more similar to each other than to polar/charged
 residues
    - in fact polar/apolar are still more similar to each other than to either positive or negative. Is a 4-way one-hot encoding fair in this case?
  - Hydrophobicity, although these seem to differ somewhat between sources
    - probably we won't include this unless we want to spend time figuring out why these are not uniform and what the correct value is

For atom-level graphs, we could include atomic mass as a feature

**Comment by DaniBodor** [comment]
@cbaakman , I found your commit which (I believe) was the first introduction of the amino acid charges. Can you remember where you got these from and/or what they represent?
https://github.com/DeepRank/deeprank-core/commit/6ebaf6261a88e03cb757a219164fb592343c1df5#diff-7d8779944e6d6c1d2df7f8fb286753302b7b95bb27aea69e66aa3634d5401f9d

**Comment by cbaakman** [comment]
> @cbaakman , I found your commit which (I believe) was the first introduction of the amino acid charges. Can you remember where you got these from and/or what they represent? [6ebaf62#diff-7d8779944e6d6c1d2df7f8fb286753302b7b95bb27aea69e66aa3634d5401f9d](https://github.com/DeepRank/deeprank-core/commit/6ebaf6261a88e03cb757a219164fb592343c1df5#diff-7d8779944e6d6c1d2df7f8fb286753302b7b95bb27aea69e66aa3634d5401f9d)

I got those from @manonreau. I copied them just to keep them in the code, but I never used them.

**Comment by DaniBodor** [comment]
> Manon mentions that it was already present in the code, before she started working on it. It could be a decision from Nicolas and Li.

@NicoRenaud, any idea where the charge data in [this commit](https://github.com/DeepRank/deeprank-core/commit/6ebaf6261a88e03cb757a219164fb592343c1df5#diff-7d8779944e6d6c1d2df7f8fb286753302b7b95bb27aea69e66aa3634d5401f9d) originated from or what it represents (because it's not actually the charge)?

I am tempted to delete this information, unless we can figure out what it is.

**Comment by NicoRenaud** [comment]
The same values are indeed there : https://github.com/DeepRank/Deeprank-GNN/blob/16b5d022aabcb7e70dba10aaf4680955e3949640/deeprank_gnn/ResidueGraph.py#L43 I have no idea where they come from, I may have been the one introducing them but I don't remember. 

The only way I could imagine to get these values would be to sum up the atomic charges of the atoms in each residues. Some of these charges are for example here : https://github.com/DeepRank/deeprank/blob/master/deeprank/features/forcefield/protein-allhdg5-4_new.top 

For example summing up the ALA values leads to a charge of 0.0 and not -0.37 as put in the data ...
It might be that we didn't add all the Hs in the residues and summed up the charge of the heavy atoms only. That would explain the -0.37 charge of ALA and the -0.64 of CYS. 

We should at the very least disable that option atm

**Comment by DaniBodor** [comment]
Thanks Nico. I summed everything up and it indeed leads to the +1/0/-1 that is expected from literature, so that's a relief.
