### ISSUE TITLE
Verify that the grid orientation is the same as in deeprank for `ProteinProteinInterfaceAtomicQuery`

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#281]
Verify that the grid generated with deeprank-core has the same orientation of the one generated with deeprank (see [deeprank/GridTools.py](https://github.com/DeepRank/deeprank/blob/master/deeprank/generate/GridTools.py)).

**Comment by cbaakman** [comment]
Working on this in #312.
