### ISSUE TITLE
Reorganize import order according to python convention

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank-core#314]
See [here](https://peps.python.org/pep-0008/#imports):

Mainly:
> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
> 
> Imports should be grouped in the following order:
> 
> 1.     Standard library imports.
> 2.     Related third party imports.
> 3.     Local application/library specific imports.
> 
> You should put a blank line between each group of imports.

Can be done using a tool like [isort](https://pycqa.github.io/isort/)

**Comment by gcroci2** [comment]
We can use isort for this https://pycqa.github.io/isort/, it does it automatically for all files

**Comment by DaniBodor** [comment]
this is now automatically implemented when working in VS code by commit [c3aacf3](vscode-file://vscode-app/c:/Users/DaniBodor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
