### ISSUE TITLE
Investigate PDBs causing `KeyError` in `QueryCollection.process`

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#338]
During the processing of the queries, we are now catching `KeyError` exceptions which come from the queries' building process, so the code keeps running without adding those data points to the hdf5 files, which are very few.

But it would be handy to understand why we have such exceptions. Models IDs that throw KeyError: BA-115668, BA-132474, BA-503344, BA-65401.
Example of traceback:
```
Traceback (most recent call last):
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/query.py", line 197, in _process_one_query
    graph = query.build(feature_modules)
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/query.py", line 820, in build
    feature_module.add_features(self._pdb_path, graph)
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/features/conservation.py", line 27, in add_features
    pssm_row = residue.get_pssm()
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/molstruct/residue.py", line 52, in get_pssm
    return pssm[self]
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/utils/pssmdata.py", line 41, in __getitem__
    return self._rows[residue]
KeyError: contact_atoms_BA-132474 M 188
```

The files needed to reproduce the error are (paths refer to Snellius locations):

- '/projects/0/einf2380/data/pMHCI/features_input_folder/exp_nmers_all_HLA_quantitative/pdb/' in which you can find the pdb models for each ID
- '/projects/0/einf2380/data/pMHCI/features_input_folder/exp_nmers_all_HLA_quantitative/pssm/' in which you can find the pssm for the peptide and the pssm for the protein MHC (2 separate files for each ID)

In each folder, the files needed can be recognized by a specific ID in the filename, like BA-115668.

**Comment by gcroci2** [comment]
Also in this case (as issue #337) I don't think it's urgent since this happens for only 4-5 data points out of 100000, but I'd like to make you aware of the issue @cbaakman

**Comment by cbaakman** [comment]
My guess is that the PSSM file misses a residue, or the PDB file has one residue extra. I will inspect the files some time.

**Comment by cbaakman** [comment]
C-terminal residue 188 is absent from BA-132474.M.pssm. But BA-132474.pdb has it. That's the problem.

I don't know where this pssm came from or how it was made. Maybe the residue is missing, because of the terminal oxygen in the pdb file.

**Comment by gcroci2** [comment]
Great you catched it. We are happy about catching the exception KeyError in the query.py in such cases, right? If yes I'll close the issue. @cbaakman

**Comment by gcroci2** [comment]
> C-terminal residue 188 is absent from BA-132474.M.pssm. But BA-132474.pdb has it. That's the problem.
> 
> I don't know where this pssm came from or how it was made. Maybe the residue is missing, because of the terminal oxygen in the pdb file.

It could be handy for @DarioMarzella and @heleen to know about this issue. I've just invited Heleen as collaborator to the repo so I can't tag her yet.

**Comment by cbaakman** [comment]
> We are happy about catching the exception KeyError in the query.py in such cases, right? If yes I'll close the issue. @cbaakman

If this one residue is missing from the PSSM file, that means the graph will have no pssm feature values for that particular node.

When we catch this error, either we remove the node or go on to the next query.

**Comment by gcroci2** [comment]
> > We are happy about catching the exception KeyError in the query.py in such cases, right? If yes I'll close the issue. @cbaakman
> 
> If this one residue is missing from the PSSM file, that means the graph will have no pssm feature values for that particular node.
> 
> When we catch this error, either we remove the node or go on to the next query.

Right now we go to the next query and we don't add that data point. I think it's fine like this, do you agree? @cbaakman

**Comment by cbaakman** [comment]
> Right now we go to the next query and we don't add that data point. I think it's fine like this, do you agree? @cbaakman

I agree.
