### ISSUE TITLE
Verify features values of `contact` submodule for grids

### ISSUE THREAD

**Issue by cbaakman** [DeepRank/deeprank-core#342]
We need to test and be sure that the deeprank-core grid data contains correct electrostatic as well as vanderwaals values, like in the original deeprank. Check that the values are the same.

**Comment by cbaakman** [comment]
It seems the cutoff (from the old deeprank) isn't applied to the deeprank core contact features. We must incorporate this also.

**Comment by cbaakman** [comment]
The grid values are not the same. I presume this has many reasons, but one of them is that we don't use exactly the same set of atoms. Another reason is that we also consider contacts between atoms in the same chain, not just between two chains.

**Comment by gcroci2** [comment]
> The grid values are not the same. I presume this has many reasons, but one of them is that we don't use exactly the same set of atoms. Another reason is that we also consider contacts between atoms in the same chain, not just between two chains.

Should this be further discussed or there is already a discussion going on (either on Slack or on GitHub)? @cbaakman

**Comment by cbaakman** [comment]
> Should this be further discussed or there is already a discussion going on (either on Slack or on GitHub)? @cbaakman

It's being discussed in #357
