### ISSUE TITLE
Bug: 'LYS' is labeled as 'neg_charged' in deeprank-GNN

### ISSUE THREAD

**Issue by ntxxt** [DeepRank/deeprank-core#349]
In residue_polarity dict, LYS' is labelled as 'neg_charged' instead of 'pos_charged', leads to generation of wrong feature. 
See below:
https://github.com/DeepRank/Deeprank-GNN/blob/16b5d022aabcb7e70dba10aaf4680955e3949640/deeprank_gnn/ResidueGraph.py

        self.residue_polarity = {'CYS': 'polar', 'HIS': 'polar', 'ASN': 'polar', 'GLN': 'polar', 'SER': 'polar', 'THR': 'polar', 'TYR': 'polar', 'TRP': 'polar',
                                 'ALA': 'apolar', 'PHE': 'apolar', 'GLY': 'apolar', 'ILE': 'apolar', 'VAL': 'apolar', 'MET': 'apolar', 'PRO': 'apolar', 'LEU': 'apolar',
                                 'GLU': 'neg_charged', 'ASP': 'neg_charged', 'LYS': 'neg_charged', 'ARG': 'pos_charged'}

But I think this bug is fixed already in deeprank-core.

**Comment by ntxxt** [comment]
I have re-trained deeprank-GNN with the corrected charge for lys and also the Kyte-Doolittle hydrophobic scale instead of the old charges (which are all negative), 
Model performance dropped a little on the BM5 benchmark.

**Comment by DaniBodor** [comment]
Indeed, in deeprankcore it is considered to have positive charge. If it should be fixed in deeprank-GNN, please open an issue there as well if you hadn't done so already.
I will close this one here now, please tag me if there's still a problem with this
