### ISSUE TITLE
Fix grid data generation

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#350]
An hdf5 file with grids should be structured like the following (example of one data point):
- residue xxx Group
  - edge_features Group
    -  features _**Datasets**_
  - ...
  - mapped_features Group
    - features **_Datasets_**
  
While is it like the following:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/55382553/217838876-ac0757ff-06d5-4089-9135-ac9b51f36a9b.png">
So the mapped_features Group contains Groups instead of directly containing Datasets with the features. We need to allineate mapped_features Group to the others. 
- [x] Modify the code to generate Datasets (directly) in mapped_features instead of Groups
- [x] Regenerate test file for grids (deeprank-core/tests/data/hdf5/1ATN_ppi.hdf5)

Additionally, by generating an example hdf5 file with the following script:
```python
from pathlib import Path
import pkg_resources as pkg
PATH_DEEPRANK_CORE = Path(pkg.resource_filename("deeprankcore", ""))
ROOT = PATH_DEEPRANK_CORE.parent
PATH_TEST = ROOT / "tests"
from deeprankcore.query import (
    QueryCollection,
    ProteinProteinInterfaceResidueQuery)
from deeprankcore.tools.target import compute_targets
from deeprankcore.utils.grid import MapMethod, GridSettings
import glob
import os
import re
import sys
import h5py
import numpy as np
import pandas as pd

points_counts = [10, 10, 10]
grid_sizes = [30.0, 30.0, 30.0]

ref_path = str(PATH_TEST / "data/ref/1ATN/1ATN.pdb")
pssm_path1 = str(PATH_TEST / "data/pssm/1ATN/1ATN.A.pdb.pssm")
pssm_path2 = str(PATH_TEST / "data/pssm/1ATN/1ATN.B.pdb.pssm")
chain_id1 = "A"
chain_id2 = "B"
pdb_paths = [
    str(PATH_TEST / "data/pdb/1ATN/1ATN_1w.pdb"),
    str(PATH_TEST / "data/pdb/1ATN/1ATN_2w.pdb"),
    str(PATH_TEST / "data/pdb/1ATN/1ATN_3w.pdb"),
    str(PATH_TEST / "data/pdb/1ATN/1ATN_4w.pdb")]

queries = QueryCollection()

for pdb_path in pdb_paths:
    # Append data points
    targets = compute_targets(pdb_path, ref_path)
    queries.add(ProteinProteinInterfaceResidueQuery(
        pdb_path = pdb_path,
        chain_id1 = chain_id1,
        chain_id2 = chain_id2,
        targets = targets,
        pssm_paths = {
            chain_id1: pssm_path1,
            chain_id2: pssm_path2
        }
    ))

# Generate graphs and save them in hdf5 files
output_paths = queries.process(
    cpu_count=1,
    prefix='1ATN_ppi_grid',
    grid_settings=GridSettings(points_counts, grid_sizes),
    grid_map_method=MapMethod.FAST_GAUSSIAN)
```
I can't open the Datasets contained in the Groups in mapped_features parent Group. I get the following error for all the features:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/55382553/217841312-a9f16ad9-6e52-40e9-ae1a-4d5113672f7a.png">

**Comment by cbaakman** [comment]
I'm not sure what software you're using. When I run your script, I can retrieve the output from the file using h5py.

**Comment by gcroci2** [comment]
> hdfview doesn't work on my linux desktop. When I run your script, I can retrieve the output from the file using h5py.

Okay I'll run it again after having merged your PR, and let's see what happens.

**Comment by cbaakman** [comment]
This may be related:
https://forum.hdfgroup.org/t/cannot-read-hdf5-data/6714

**Comment by cbaakman** [comment]
@gcroci2 I installed the latest hdfview and now I can reproduce your problem.

It seems uncompressed unchunked datasets can be viewed. But chunked compressed grid data cannot.

**Comment by gcroci2** [comment]
> @gcroci2 I installed the latest hdfview and now I can reproduce your problem.
> 
> It seems uncompressed unchunked datasets can be viewed. But chunked compressed grid data cannot. I do think compression is necessary. Grid data is quite sparse.

Are the grid data compressed in original deeprank?

**Comment by cbaakman** [comment]
> Are the grid data compressed in original deeprank?
No, they use a different system to remove sparsity:
https://github.com/DeepRank/deeprank/blob/master/deeprank/tools/sparse.py

That's why in the original deeprank, data is stored under ../value and ../index .

**Comment by gcroci2** [comment]
> https://github.com/DeepRank/deeprank/blob/master/deeprank/tools/sparse.py

I see, but here we didn't have /index in the mapped_features groups, only compressed values. I also think is fine as they are, so compressed.
