### ISSUE TITLE
Add -FLIP and -Quiet option to reduce

### ISSUE THREAD

**Issue by DarioMarzella** [DeepRank/deeprank-core#375]
When using _reduce_  to add hydrogens ( https://github.com/DeepRank/deeprank-core/blob/92bf4cc207e891a65d10dfce598ea569408497ce/deeprankcore/utils/buildgraph.py#L21 ) the -FLIP option should be used to correct flipped ASP, HIS and GLN ( see details here: https://www.sciencedirect.com/science/article/pii/S0969212611002851 ).

Also, -Quiet can be added to prevent useless verbose output.

**Comment by DaniBodor** [comment]
Hi @DarioMarzella , can you maybe create a PR where you implement this and then tag one of us for review?

Thanks!

**Comment by DaniBodor** [comment]
superseded by #439
