### ISSUE TITLE
Bug: Trainer error when only dataset_test and pre_trained model is used 

### ISSUE THREAD

**Issue by ntxxt** [DeepRank/deeprank-core#403]
When use dataset_test only and pre_trained model to do fitting, 

caused AttributeError: 'Trainer' object has no attribute 'classes_to_index' at following line 
https://github.com/DeepRank/deeprank-core/blob/dbaebd006eff3c1da0f82a8d8a0284bd0ba5a841/deeprankcore/trainer.py#L802

**Comment by gcroci2** [comment]
I know how to easily fix it, it's still needed, right? @ntxxt

**Comment by ntxxt** [comment]
I fixed it already thanks...just to point out there is a tiny bug @gcroci2

**Comment by gcroci2** [comment]
> I fixed it already thanks...just to point out there is a tiny bug @gcroci2

Great! I was confused but the issue closed and then reopened. Could you open a PR for fixing it in the code-base as well? Otherwise, I can do it myself, but if you've already done it, why do the same job twice? ;)

**Comment by DaniBodor** [comment]
Can this issue be closed?
