### ISSUE TITLE
Handle grids features that cannot be summed

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#409]
Discuss how to handle grids features that cannot be summed (e.g. PSSM for pMHC complexes). We will add information to the issue when we'll have a clearer idea about the action points.

**Comment by cbaakman** [comment]
How are such features not summable? PSSM features are numerical.
I think this issue needs additional explanation.

**Comment by gcroci2** [comment]
PSSM features are summable in terms of types, but the sum doesn't have a scientific meaning. I think that @LilySnow can motivate further.

**Comment by LilySnow** [comment]
In the original DeepRank-cnn, we represent chains in separate grids, for example, MHC in one grid and the peptide in another grid. DeepRank has an option to add these two grids up into one grid. 

For the peptide:MHC system, the MHC has PSSM but peptide does not have it. So peptide could be represented by one-hot encoding, for example. PSSM and one-hot encoding cannot be simply summed up. To tackle this, we could add an embedding layer first for the MHC grid and the peptide grid before adding them into one grid. 

For GNN, the MHC node has PSSM as the node feature and the peptide node has one-hot encoding. This is not compatible also. We could do similarly by adding an embedding layer.

**Comment by gcroci2** [comment]
If you all agree, I think that this should not be a feature of the package, but something that each user is free to implement by himself/herself. If you use PSSM, the files you provide need to be already right, to use the package as it is. For different usages, it's up to the user to edit the package or write new modules for handling it. @LilySnow @cbaakman

**Comment by cbaakman** [comment]
I agree. There are too many different possibilities to have this all implemented. Let the user decide what he/she wants.
