### ISSUE TITLE
Fix PSSM checks

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#424]
There are few issues related to PR #401; in cases in which amino acids in pssm files do not match pdb file:
- [x] Output a less verbose message for each
- [x] Only check pssms if relevant feature module is selected. Even if I'm selecting 'components' and 'contact' modules features it's checking the PSSM, which should not happen I think (I'm not selecting the module for the PSSM which is 'conservation').

**Comment by DaniBodor** [comment]
On second thought, I disagree with task 1 here. I think if task 3 is fixed, then the error should remain and hdf5 files shouldn't be created. Otherwise the danger is that users will not notice the warnings and create faulty hdf5 files and use them.
