### ISSUE TITLE
problem with check_pssm 

### ISSUE THREAD

**Issue by rgayatri** [DeepRank/deeprank-core#428]
I am trying to preprocess variant data using SingleResidueVariantAtomicQuery.
Here is the error I get

```
Graph/Query with ID atomic-graph:A:14:Arginine->Cysteine:pdb2g98 ran into an Exception (ValueError: Amino acids in PSSM files do not match pdb file for pdb2g98.ent.), and it has not been written to the hdf5 file. More details below:
Amino acids in PSSM files do not match pdb file for pdb2g98.ent.
Traceback (most recent call last):
  File "/mnt/home2/gayatrir/deeprank-core/deeprankcore/query.py", line 65, in _check_pssm
    if pdb_truth[residue] != pssm_data[residue]:
KeyError: 'B0001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home2/gayatrir/deeprank-core/deeprankcore/query.py", line 244, in _process_one_query
    graph = query.build(feature_modules)
  File "/mnt/home2/gayatrir/deeprank-core/deeprankcore/query.py", line 570, in build
    structure = self._load_structure(self._pdb_path, self._pssm_paths, include_hydrogens, load_pssms)
  File "/mnt/home2/gayatrir/deeprank-core/deeprankcore/query.py", line 129, in _load_structure
    _check_pssm(pdb_path, pssm_paths)
  File "/mnt/home2/gayatrir/deeprank-core/deeprankcore/query.py", line 68, in _check_pssm
    raise ValueError(error_message) #pylint: disable = raise-missing-from
ValueError: Amino acids in PSSM files do not match pdb file for pdb2g98.ent.
```

My task does not involve inclusion of multiple chains. 
Also, I note that residues in pdb and pssm are identical. 

Code to reproduce:
```
from deeprankcore.query import QueryCollection, SingleResidueVariantAtomicQuery
from deeprankcore.features import components, conservation, contact, surfacearea
from deeprankcore.utils.grid import GridSettings, MapMethod
from deeprankcore.domain.aminoacidlist import (arginine, cysteine)
from deeprankcore.domain import targetstorage as targets

queries.add(SingleResidueVariantAtomicQuery(
    pdb_path = "/home/gayatrir/DATA/pdb/pdb2g98.ent",
    chain_id = "A",
    residue_number = 14,
    insertion_code = None,
    wildtype_amino_acid = arginine,
    variant_amino_acid = cysteine,
    pssm_paths = {"A": "/mnt/csb/DeepRank-Mut-DATA/pssm_update/2g98.A.pdb.pssm"},
    targets={targets.BINARY: 1},
    radius= 10.0,
    distance_cutoff= 4.5,
    ))


```

**Comment by gcroci2** [comment]
So the _check_pssm method gives an error even if the PSSM file is correct, right? @rgayatri

**Comment by rgayatri** [comment]
Yes indeed. The key error however is for chain B which I do not provide in my pssm_path. 
The code seems to search for pssms for all chains in the pdb file

**Comment by DaniBodor** [comment]
I ran this test script (using pytest) on your data files (from slack) and it ran without errors:

> from deeprankcore.domain import targetstorage as targets
> from deeprankcore.domain.aminoacidlist import arginine, cysteine
> from deeprankcore.features import (components, conservation, contact,
>                                    surfacearea)
> from deeprankcore.query import QueryCollection, SingleResidueVariantAtomicQuery
> from deeprankcore.utils.grid import GridSettings, MapMethod
> 
> 
> def test_something():
>     queries = QueryCollection()
> 
>     queries.add(SingleResidueVariantAtomicQuery(
>         pdb_path = "/home/dbodor/git/DeepRank/deeprank-core/tests/data/Gayatritest/pdb2g98.ent",
>         chain_id = "A",
>         residue_number = 14,
>         insertion_code = None,
>         wildtype_amino_acid = arginine,
>         variant_amino_acid = cysteine,
>         pssm_paths = {"A": "/home/dbodor/git/DeepRank/deeprank-core/tests/data/Gayatritest/2g98.A.pdb.pssm"},
>         targets={targets.BINARY: 1},
>         radius= 10.0,
>         distance_cutoff= 4.5,
>         ))
> 
>     queries.process(feature_modules=conservation)

When is the last time you pulled main? There were some changes to `_test_pssm` last week, so maybe that's the difference?

**Comment by DaniBodor** [comment]
> I ran this test script on the main branch (using pytest) on your data files (from slack) and it ran without errors:
> 
> > from deeprankcore.domain import targetstorage as targets
> > from deeprankcore.domain.aminoacidlist import arginine, cysteine
> > from deeprankcore.features import (components, conservation, contact,
> > surfacearea)
> > from deeprankcore.query import QueryCollection, SingleResidueVariantAtomicQuery
> > from deeprankcore.utils.grid import GridSettings, MapMethod
> > def test_something():
> > queries = QueryCollection()
> > ```
> > queries.add(SingleResidueVariantAtomicQuery(
> >     pdb_path = "/home/dbodor/git/DeepRank/deeprank-core/tests/data/Gayatritest/pdb2g98.ent",
> >     chain_id = "A",
> >     residue_number = 14,
> >     insertion_code = None,
> >     wildtype_amino_acid = arginine,
> >     variant_amino_acid = cysteine,
> >     pssm_paths = {"A": "/home/dbodor/git/DeepRank/deeprank-core/tests/data/Gayatritest/2g98.A.pdb.pssm"},
> >     targets={targets.BINARY: 1},
> >     radius= 10.0,
> >     distance_cutoff= 4.5,
> >     ))
> > 
> > queries.process(feature_modules=conservation)
> > ```
> 
> When is the last time you pulled main? There were some changes to `_check_pssm` last week, so maybe that's the difference?

never mind, I ran build method and that's when it crashed. 
I will look further into it. My guess: it searches for all residues present in the pdb file, and because there is a B chain in the file it will detect missing residues. I'll try to fix this quickly

**Comment by rgayatri** [comment]
Based on conversation from slack- Can this check be changed to a warning instead of an error?
