### ISSUE TITLE
DSSP dependency install instructions

### ISSUE THREAD

**Issue by GTukkers** [DeepRank/deeprank-core#436]
**Describe the bug**
The link given for the installation of the dependencie of DSSP is outdated, and leads with multiple steps to an outdated version of DSSP.  Should/can this still be used or should the newer version of DSSP at https://github.com/pdb-redo/dssp be used?

**Comment by DaniBodor** [comment]
The package has been tested with both DSSP 3 and DSSP 4 (although the continuous integration only runs on DSSP4). Depending on your system (ubuntu version), `sudo apt install dssp` will install one of these. It should work either way, but probably safest to install newest version of DSSP.

I will update the readme.

**Comment by GTukkers** [comment]
Good to know, just one more question about it. What to do if you don't have sudo priveledges, do you only need to install DSSP or also the requirements which are necessary for DSSP?

**Comment by DaniBodor** [comment]
you need the requirements as well, otherwise dssp won't work
