### ISSUE TITLE
Add unit tests for HDF5DataSet class parameters

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#82]
Parameters in HDF5DataSet for which we need either examples or unit tests:

- [ ] transform - **to do**
- [ ] pre_transform - *nice to have*
- [ ] dict_filter - *nice to have*
- [ ] edge_feature_transform. Rationale for the default value (`lambda x: np.tanh(-x / 2 + 2) + 1`)?   - *nice to have*

**Comment by cbaakman** [comment]
I don't see transform being called anywhere. Is it even needed?

**Comment by gcroci2** [comment]
> I don't see transform being called anywhere. Is it even needed?

It could be useful to normalize a feature for example or to apply some transformation to it. Same for the other parameters
