### ISSUE TITLE
Use only edges with covalent feature set to True for clustering

### ISSUE THREAD

**Issue by svenvanderburg** [DeepRank/deeprank-core#96]
In #92 we started clustering all edges instead of just 'internal edges'. We are clustering based on proximity between nodes. This makes less sense than clustering only on internal edges, which usually represent covalent bonds. We can still have the same behavior if we use only the edges with the covalent feature set to True.

**Comment by svenvanderburg** [comment]
@cbaakman did you close this on accident?

**Comment by cbaakman** [comment]
Sorry! I must have closed the wrong issue.
